### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by blairfancy** [opacam/python3-tmdb3#5]
when try to install through setup.py i got error :
f'"{datestr}" is not a supported date format. '

**Comment by opacam** [comment]
Mmmm...this is strange, there is no such entry in `setup.py` file. Hard to help with only this information...so...maybe you could give more information like:
  - What version of python do you use?
  - What command do you use for the install?
  - Maybe the log output of the install command?

**Comment by blairfancy** [comment]
```
` sudo -EH pip3 install -e git+https://github.com/opacam/python3-tmdb3.git#egg=tmdb3
Obtaining tmdb3 from git+https://github.com/opacam/python3-tmdb3.git#egg=tmdb3
  Cloning https://github.com/opacam/python3-tmdb3.git to ./src/tmdb3
  Running command git clone -q https://github.com/opacam/python3-tmdb3.git /mnt/data1/encode/FullDisc/src/tmdb3
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsl2av064
       cwd: /mnt/data1/encode/FullDisc/src/tmdb3
  Complete output (23 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-2ig8f678/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-2ig8f678/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-2ig8f678/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-2ig8f678/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 16, in <module>
      pkg = __import__('tmdb3')
    File "/mnt/data1/encode/FullDisc/src/tmdb3/tmdb3/__init__.py", line 3, in <module>
      from .tmdb_api import (
    File "/mnt/data1/encode/FullDisc/src/tmdb3/tmdb3/tmdb_api.py", line 39
      f'"{datestr}" is not a supported date format. '
                                                    ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsl2av064 Check the logs for full command output.
```


here are output window.

**Comment by opacam** [comment]
Aaaa... just what I though, the problem is that you use python version 3.5, you need at least python 3.6 since we made use of `python 3 f-strings` (introduced in python version 3.6).

**Comment by blairfancy** [comment]
Issue occurred on Ubuntu 16.04 but work properly on Ubuntu 18.04
